/**
 * 规则 ID → 中文名称 + 预览示例映射
 *
 * 供包详情「着色规则引用区」展示：
 *   - name：规则的中文语义名（未登记的 ID 回退显示原始 ID）
 *   - sample：预览示例（带符号的 Markdown 样例，用于右侧效果预览渲染）
 *
 * 命名约定：
 *   - md_* / html / kbd 为 Markdown 语法类，示例为对应语法符号
 *   - 其余为提示词 DSL 领域类，示例取自规则正则的典型命中形态
 */

/** 规则显示名映射（ID → 中文） */
export const RULE_ID_NAMES: Record<string, string> = {
  // ---- Markdown 语法类 ----
  md_frontmatter: '元数据起始线',
  md_heading: '标题',
  md_bold: '粗体',
  md_italic: '斜体',
  md_strikethrough: '删除线',
  md_highlight: '高亮',
  md_subscript: '下标',
  md_superscript: '上标',
  md_code_fence: '代码块围栏',
  md_inline_code: '行内代码',
  md_mermaid: '图表代码块',
  md_link: '外部链接',
  md_image: '图片引用',
  md_wiki_link: '双链',
  md_anchor_link: '锚点链接',
  md_tag: '标签',
  md_emoji_shortcode: '表情代码',
  md_task_list: '任务列表',
  md_list_item: '列表项',
  md_footnote_ref: '脚注引用',
  md_footnote_def: '脚注定义',
  md_math_inline: '行内公式',
  md_math_block: '块级公式',
  md_blockquote: '引用块',
  md_nested_quote: '嵌套引用',
  md_callout: '标注框',
  md_callout_meta: '标注元数据',
  md_admonition: '警示块',
  md_hr: '水平分割线',
  md_table_sep: '表格分隔行',
  md_table_row: '表格行',
  md_definition: '定义列表',
  md_block_id: '块 ID',
  md_comment: '注释',
  md_yaml_key: 'YAML 属性键',
  kbd_tag: '键盘键标签',
  html_tag: 'HTML 标签',

  // ---- 提示词 DSL 符号类 ----
  block_wrapper: '区块标记',
  shot_header: '分镜头头',
  asset_ref: '资源引用',
  asset_bracket: '资源方括号',
  param_key: '参数键',
  dialogue_cn: '中文台词',
  dialogue_en: '英文台词',
  constraint: '约束关键字',
  tech_param: '技术参数',
  parenthetical: '括号补充',
  variable: '变量占位',
  role_tag: '角色标签',
  instruction: '指令标记',
  emphasis_weight: '权重强调',
  lora_ref: 'LoRA 引用',
  bracket_strong: '强括号',
  bracket_weak: '弱括号',
  quality_tag: '质量标签',
  sd_negative_header: 'SD 负面目眉',
  audio_ref: '音频引用',
  audio_tone: '音频音调',
  audio_sfx: '音效标记',
  sd_parameter: 'SD 参数',

  // ---- 通用增强类 ----
  timestamp: '时间戳',
  version_number: '版本号',
  url_link: 'URL 链接',
  file_path: '文件路径',
  cli_command: '命令行',
  key_value: '键值对',
  reference_marker: '引用标记',
  separator: '分隔符',
  antml_tag: 'ANTML 标签',
  function_results_tag: '函数结果标签',
  xml_block: 'XML 块',
  chat_token: '对话令牌',
  llama3_token: 'Llama3 令牌',
  gemma_token: 'Gemma 令牌',
  llama2_sys: 'Llama2 系统段',
  workflow_sep: '工作流分隔',
  json_schema_key: 'JSON Schema 键',
  jinja_control: 'Jinja 控制符',
  workflow_node: '工作流节点',
  email: '邮箱',
  ip_address: 'IP 地址',
  mac_address: 'MAC 地址',
  uuid: 'UUID',
  hex_color: '十六进制色值',
  css_color_func: 'CSS 颜色函数',
  geo_coord: '地理坐标',
  currency: '货币金额',
  percentage: '百分比',
  measurement: '度量数值',
  shot_id: '镜头编号',
  segment_header: '段落头',
  module_header: '模块头',
  dialogue_speaker: '说话人标记',
  character_def: '角色定义',
  book_title: '书名号',
  cn_chapter: '中文章节',
  time_range: '时间范围',
  section_note: '小节注释',
  ssml_tag: 'SSML 标签',
  lyric_section: '歌词段落',
  suno_meta: 'Suno 元标记',
  avatar_directive: '数字人指令',
  copilot_formula: '公式块',
  react_marker: 'React 标记',
  cot_trigger: '思维链触发',
  model_identifier: '模型标识',
  comfyui_node: 'ComfyUI 节点',
  pika_parameter: 'Pika 参数',
  runway_parameter: 'Runway 参数',
  translation_marker: '翻译标记',
  fewshot_marker: '少样本标记',
  gen3d_platform: '3D 生成平台',
  explicit_identifier: '显式标识符',
  explicit_string: '显式字符串',
  constraint_absolute: '绝对约束词',
  constraint_soft: '软约束词',
  param_key_strict: '严格参数键',
  dialogue_cn_strict: '严格中文台词',
  parenthetical_strict: '严格括号补充',
  parenthetical_half: '半角括号补充',

  // ---- 运行时生成的规则 ----
  custom_inline_rule: '内联自定义规则',
};

/** 规则预览示例映射（ID → Markdown 示例文本） */
export const RULE_ID_SAMPLES: Record<string, string> = {
  // Markdown 语法类
  md_frontmatter: '---',
  md_heading: '## 标题文字',
  md_bold: '**粗体文本**',
  md_italic: '*斜体文本*',
  md_strikethrough: '~~删除文本~~',
  md_highlight: '==高亮文本==',
  md_subscript: 'H~2~O',
  md_superscript: 'x^2^',
  md_code_fence: '```js 代码块',
  md_inline_code: '`行内代码`',
  md_mermaid: '```mermaid 图表',
  md_link: '[链接文字](https://example.com)',
  md_image: '![图片描述](image.png)',
  md_wiki_link: '[[笔记名称]]',
  md_anchor_link: '[跳转](#锚点)',
  md_tag: '#标签名',
  md_emoji_shortcode: ':smile:',
  md_task_list: '- [x] 已完成任务',
  md_list_item: '- 列表项目',
  md_footnote_ref: '见脚注[^1]',
  md_footnote_def: '[^1]: 脚注说明',
  md_math_inline: '$E=mc^2$',
  md_math_block: '$$ 公式块',
  md_blockquote: '> 引用内容',
  md_nested_quote: '>> 嵌套引用',
  md_callout: '> [!note] 标注',
  md_callout_meta: '> [!note]+ 折叠',
  md_admonition: '!!! warning 警示',
  md_hr: '---',
  md_table_sep: '| --- | --- |',
  md_table_row: '| 单元格 | 内容 |',
  md_definition: ': 定义内容',
  md_block_id: '段落标识 ^block-id',
  md_comment: '%% 隐藏注释 %%',
  md_yaml_key: 'tags: 标签值',
  kbd_tag: '<kbd>Ctrl</kbd>',
  html_tag: '<div>内容</div>',

  // 提示词 DSL 类（示例为典型命中形态）
  block_wrapper: '【整体设定】',
  shot_header: '@分镜1 场景描述',
  asset_ref: '@图1 素材引用',
  param_key: '镜头语言：推镜头',
  dialogue_cn: '「角色台词」',
  constraint: '必须包含 · 要求',
  tech_param: '4K · 60fps',
  role_tag: '@主角 角色名',
  emphasis_weight: '(重点强调:1.3)',
  lora_ref: '<lora:风格名:0.8>',
  quality_tag: 'best quality',
  audio_ref: '@音1 背景音乐',
  url_link: 'https://example.com/path',
  file_path: 'src/main.ts',
  cli_command: 'npm run build',
  timestamp: '2026-09-12 16:30',
  version_number: 'v2.6.1',
  email: 'user@example.com',
  uuid: 'a1b2c3d4-e5f6',
  hex_color: '#ef4444',
  percentage: '85%',
  measurement: '1920x1080',
  currency: '$199.99',
  time_range: '09:00-18:00',
  book_title: '《三体》',
  cn_chapter: '第三章 标题',
  geo_coord: '39.9°N, 116.4°E',
  model_identifier: 'gpt-4o-mini',
  comfyui_node: 'KSampler 节点',
  jinja_control: '{% if 条件 %}',
  json_schema_key: '"type": "object"',
  chat_token: '<|im_start|>',
  ssml_tag: '<speak>语音标记</speak>',
  suno_meta: '[verse] 段落标记',
  explicit_identifier: '「显式标识」',
  explicit_string: '『显式字符串』',
  md_table_row_v2: '| 示例 |',
};

/** 获取规则中文名（未登记回退原始 ID） */
export function getRuleDisplayName(ruleId: string): string {
  return RULE_ID_NAMES[ruleId] ?? ruleId;
}

/** 获取规则预览示例（未登记回退空串） */
export function getRuleSample(ruleId: string): string {
  return RULE_ID_SAMPLES[ruleId] ?? '';
}